#FROM nvidia/cuda12.1.1-cudnn8-devel-ubuntu22.04

FROM xilinx/vitis-ai:1.4.1.978



ENV PATH=/opt/vitis_ai/conda/bin:$PATH



COPY install_reqs.sh /workspace/install_reqs.sh
RUN /workspace/install_reqs.sh

RUN  echo "conda activate vitis-ai-pytorch" >> /root/.bashrc
RUN  echo "conda activate vitis-ai-pytorch" >> /home/vitis-ai-user/.bashrc

