FROM xilinx/vitis-ai-pytorch-cpu:latest



ENV PATH=/opt/vitis_ai/conda/bin:$PATH



COPY install_reqs.sh /workspace/install_reqs.sh
RUN /workspace/install_reqs.sh

RUN  echo "conda activate vitis-ai-pytorch" >> ~/.bashrc

